### ISSUE TITLE
relecture doc v1.1_rc3

### ISSUE THREAD

**Issue by battmanux** [hand-e-fr/OpenHosta#110]
il y a tjs un `cd OpenHosta-dev` en étape 2 pour une install de la version dev
peut être ajouter un git checkout <tag ou branche> pour ne par être sur le main

"Check that you have the correct version." <- ajouter "from python"

**dans la doc:**
`def find_first_name(sentence:str)->Personn:`
je ne trouve pas Personn dans le dictionaire anglais d'oxford

**__sugest__**:
je propose j'ajouter:
```python
from OpenHosta import emulate, config, suggest

suggest(find_occurence_of_a_word)
```

```python
def suggest(func, *arg, **kargs):
    func.__suggest__(func, *arg, **kargs)
```

thought pourait être renommé think pour être plus impératif et moins déclaratif (python est impératif)

**Comment by battmanux** [comment]
ajout dans la doc:
```OpenHosta.__version__```

Il fait ajouter import OpenHosta pour que la ligne fonctionne

OpenHosta.__version__ renvoie "1.1.0" alors que je suis en rc3. comment je vais faire la différence pour la rc4 ?

**Comment by MerlinDEVILLARD** [comment]
> OpenHosta.version renvoie "1.1.0" alors que je suis en rc3. comment je vais faire la différence pour la rc4 ?
J'ai fais une erreur pour la rc3 en effet. On peut utiliser ça à la place:
```python
pip show OpenHosta
```
Avec cette commande, c'est la rc3 qui s'affiche !

**Comment by MerlinDEVILLARD** [comment]
> je pensais que tu l'inclue dans OpenHosta.
suggest(find_occurence_of_a_word) me semble assez propre et explicite comme appel non ?

J'ai testé la feature et ça me parait assez explicit, cette feature sera donc dans la rc4.
