### ISSUE TITLE
Hosta Injected functions does not support List[...] return type 

### ISSUE THREAD

**Issue by battmanux** [hand-e-fr/OpenHosta#13]
- Version: 1.0
- Severity: non blocking

## Sample Code

```python
import os
from typing import List
from OpenHosta import emulate, config

config.set_default_apiKey(os.environ["OPENAI_API_KEY"])

def foo() -> List[str]:
   """make a list of foo words"""
  return emulate()

```

## Expected Behavior

`foo()` shoud return a list of string

## Unexpected Behavior

`foo()` throw an error message : 

```
    if issubclass(return_type, BaseModel):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class
```

## Workaround 

Declare List[str] as a pydantic type:

```python

class StrList(BaseModel):
  data: List[str]

def foo() -> StrList:
   """make a list of foo words"""
  return emulate()
```

**Comment by ramosleandre** [comment]
[X] add multiple type from typing like : List, Dict, Tuple, Set, Frozenset, Union, Annotated, Optionnal, Literal, Deque, Iterable, Sequence, Mapping

- [ ] Verify in `emulate` if the type is respected or not
