### ISSUE TITLE
Léandre has skill issues, can't even release 1.2

### ISSUE THREAD

**Issue by MerlinDEVILLARD** [hand-e-fr/OpenHosta#134]
[Léandre be like](https://media.licdn.com/dms/image/v2/D4E12AQHgfw4XjQOXNA/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1655462140904?e=2147483647&v=beta&t=WsrloGwqDJBEY8IcYb0Pe2LRpFTpMiYO7aLcx9spdqM)

**Comment by ramosleandre** [comment]
all good now
