### ISSUE TITLE
emulated function should recognize pydantic returned objects

### ISSUE THREAD

**Issue by battmanux** [hand-e-fr/OpenHosta#8]
# A clear and concise description of the proposed enhancement.

OpenHosta shoud be able to return valid [pydantic](https://docs.pydantic.dev/latest/) objects.

# Reasons why you believe this enhancement is necessary.

It is a very appreciated function of LangChain.

# Any other relevant information (code examples, links to other projects, etc.).

This shoud work:

```python
from datetime import datetime
from typing import Tuple

from pydantic import BaseModel
import OpenHosta

class WorkingDayReport(BaseModel):
    working_day: datetime
    am_arrival_time: datetime
    am_deprture_time: datetime
    pm_arrival_time: datetime
    pm_departure_time: datetime
    working_hours: Tuple[int, int]

@llm.emulate                 
def get_working_time(email:str)->WorkingDayReport: 
   """
   Convert a mail message into a Delivery class.  
   """
   pass 

msg = """
De: Merlin Devillard<devillardmerlin01@gmail.com>
​A: Emmanuel BATT
​Subject: Horaire Merlin 04/07/2024

8h50 - 11h50  13h50 - 18h00
"""
get_working_time(msg)    
```

**Comment by MerlinDEVILLARD** [comment]
We have taken your request into account and resolved it in the latest version 1.0.2. Please check the documentation for detailed explanations.
