### ISSUE TITLE
Inconsistent File Extension Handling in `save_examples` and `load_examples` Functions

### ISSUE THREAD

**Issue by WilliamJlvt** [hand-e-fr/OpenHosta#86]
## Description:

https://github.com/hand-e-fr/OpenHosta/blob/8a51e5a590d1ab04ab67575765ec2d575518e498/doc/Docs.md?plain=1#L367

There is an inconsistency in how file extensions are handled between the `save_examples` and `load_examples` functions in the documentation for the `example` function. Specifically:

- When using `save_examples`, the `hosta_path` parameter does not require specifying a file extension. The function automatically appends the `.jsonl` extension.
- Conversely, when using `load_examples`, the `hosta_path` parameter requires the file extension to be explicitly specified (e.g., `translate_func_example.jsonl`).
This inconsistency can lead to confusion for users. It is unclear whether the .jsonl extension is mandatory and universally applied, or if there is flexibility to use different formats.

## Request:
**Clarification in Documentation**: Please clarify in the documentation whether the `.jsonl` extension is the only supported format for both saving and loading examples. If it is indeed universal, consider updating the `load_examples` function to automatically append the `.jsonl` extension if it is not provided, similar to `save_examples`.

**Comment by ramosleandre** [comment]
fixed with the doc in 1.2
