### ISSUE TITLE
OpenHosta shall be compatible with local models as ollama phi-3

### ISSUE THREAD

**Issue by battmanux** [hand-e-fr/OpenHosta#9]
# A clear and concise description of the proposed enhancement.

OpenHosta shall support local models for data security concerns. running ollama locally is a convenient way of securing data excanged with LLMs. ollama exposes an OpenAI compatible API. 

# Reasons why you believe this enhancement is necessary.

Data security when emulating in USA servers is not accepted by users

# Any other relevant information (code examples, links to other projects, etc.).

 - As per July 2024, ollama interface does not support list in "message" par of the json query sent to the REST API. 
 - What about using LangChain under the hood for model connection ?
 
 I expect this to work:

```bash
curl -fsSL https://ollama.com/install.sh | sh
ollama pull phi-3
```

```python
llm = OpenHosta.emulator(
   model="phi-3",
   host="https://localhost:11431",
   api_key="This_is_my_api_key",
   creativity=0.7,
   diversity=0.5
)
````

**Comment by MerlinDEVILLARD** [comment]
We have taken your request into account and resolved it in the latest version 1.0.2. Please check the documentation for detailed explanations.
